namespace XtremeModels
{
    public class PartyModel
    {
        public int Mkey { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Uid { get; set; }
        public int Uid2 { get; set; }
        public string Mob1 { get; set; }
        public string Mob2 { get; set; }
        public string Mob3 { get; set; }
        public string Mob4 { get; set; }
        public string email { get; set; }
        public string wn { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public bool Mrk { get; set; }
        public bool Plock { get; set; }
        public double On_per { get; set; }
        public bool Actac { get; set; }
        public bool Acind { get; set; }
        public string Bindc { get; set; }
        public bool Am { get; set; }
        public bool Bmod { get; set; }
        public int Cc { get; set; }
        public double Plimit { get; set; }
        public double Cbal { get; set; }
        public double Tbal { get; set; }
        public double Sfc1 { get; set; }
        public double Sfc2 { get; set; }
        public double Sfc3 { get; set; }
        public double Sfc4 { get; set; }
        public double Sfc_com { get; set; }
        public double Sfc_own { get; set; }
        public double Std1 { get; set; }
        public double Std2 { get; set; }
        public double Std3 { get; set; }
        public double Std_com { get; set; }
        public double Std_own { get; set; }
        public double S_100 { get; set; }
        public double S_200 { get; set; }
        public double S_750 { get; set; }
        public double S_1500 { get; set; }
        public double S_7500 { get; set; }
        public double S_15000 { get; set; }
        public double S_25000 { get; set; }
        public double S_40000 { get; set; }
        public double S_GLT { get; set; }
        public double S_own { get; set; }
        public double D_100 { get; set; }
        public double D_200 { get; set; }
        public double D_750 { get; set; }
        public double D_1500 { get; set; }
        public double D_7500 { get; set; }
        public double D_15000 { get; set; }
        public double D_25000 { get; set; }
        public double D_40000 { get; set; }
        public double D_GLT { get; set; }
        public double D_own { get; set; }
        public double Dp_100 { get; set; }
        public double Dp_200 { get; set; }
        public double Dp_750 { get; set; }
        public double Dp_1500 { get; set; }
        public double Dp_7500 { get; set; }
        public double Dp_15000 { get; set; }
        public double Dp_25000 { get; set; }
        public double Dp_40000 { get; set; }
        public double Dp_GLT { get; set; }
        public double Dp_own { get; set; }
        public double P_100 { get; set; }
        public double P_200 { get; set; }
        public double P_750 { get; set; }
        public double P_1500 { get; set; }
        public double P_7500 { get; set; }
        public double P_15000 { get; set; }
        public double P_25000 { get; set; }
        public double P_40000 { get; set; }
        public double P_GLT { get; set; }
        public double P_own { get; set; }
        public double Zop_com { get; set; }
        public double Zak_com { get; set; }
        public double Zxak_com { get; set; }
        public double Ztd_com { get; set; }
        public double Zxtd_com { get; set; }
        public double Zfc_com { get; set; }
        public double Zdot_com { get; set; }
        public double Zd6_com { get; set; }
        public double Op_com { get; set; }
        public double Op_win1 { get; set; }
        public double Op_win2 { get; set; }
        public double Ak_com { get; set; }
        public double Ak_win1 { get; set; }
        public double Ak_win2 { get; set; }
        public double Xak_com { get; set; }
        public double Xak_win1 { get; set; }
        public double Xak_win2 { get; set; }
        public double Td_com { get; set; }
        public double Td_win1 { get; set; }
        public double Td_win2 { get; set; }
        public double Xtd_com { get; set; }
        public double Xtd_win1 { get; set; }
        public double Xtd_win2 { get; set; }
        public double Fc_com { get; set; }
        public double Fc_win1 { get; set; }
        public double Fc_win2 { get; set; }
        public double Dot_com { get; set; }
        public double Dot_win1 { get; set; }
        public double D6_com { get; set; }
        public double D6_win1 { get; set; }
        public double Dop_com { get; set; }
        public double Dop_win1 { get; set; }
        public double Dop_win2 { get; set; }
        public double Dak_com { get; set; }
        public double Dak_win1 { get; set; }
        public double Dak_win2 { get; set; }
        public double Dxak_com { get; set; }
        public double Dxak_win1 { get; set; }
        public double Dxak_win2 { get; set; }
        public double Dtd_com { get; set; }
        public double Dtd_win1 { get; set; }
        public double Dtd_win2 { get; set; }
        public double Dxtd_com { get; set; }
        public double Dxtd_win1 { get; set; }
        public double Dxtd_win2 { get; set; }
        public double Dfc_com { get; set; }
        public double Dfc_win1 { get; set; }
        public double Dfc_win2 { get; set; }
        public double Ddot_com { get; set; }
        public double Ddot_win1 { get; set; }
        public double Dd6_com { get; set; }
        public double Dd6_win1 { get; set; }
        public double Pop_com { get; set; }
        public double Pop_win1 { get; set; }
        public double Pop_win2 { get; set; }
        public double Pak_com { get; set; }
        public double Pak_win1 { get; set; }
        public double Pak_win2 { get; set; }
        public double Pxak_com { get; set; }
        public double Pxak_win1 { get; set; }
        public double Pxak_win2 { get; set; }
        public double Ptd_com { get; set; }
        public double Ptd_win1 { get; set; }
        public double Ptd_win2 { get; set; }
        public double Pxtd_com { get; set; }
        public double Pxtd_win1 { get; set; }
        public double Pxtd_win2 { get; set; }
        public double Pfc_com { get; set; }
        public double Pfc_win1 { get; set; }
        public double Pfc_win2 { get; set; }
        public double Pdot_com { get; set; }
        public double Pdot_win1 { get; set; }
        public double Pd6_com { get; set; }
        public double Pd6_win1 { get; set; }
        public double Lmt_op { get; set; }
        public double Lmt_ak { get; set; }
        public double Lmt_xak { get; set; }
        public double Lmt_td { get; set; }
        public double Lmt_xtd { get; set; }
        public double Lmt_fc { get; set; }
        public double Lmt_dot { get; set; }
        public double Lmt_d6 { get; set; }
        public double Lop_com { get; set; }
        public double Lop_win1 { get; set; }
        public double Lop_win2 { get; set; }
        public double Lak_com { get; set; }
        public double Lak_win1 { get; set; }
        public double Lak_win2 { get; set; }
        public double Lxak_com { get; set; }
        public double Lxak_win1 { get; set; }
        public double Lxak_win2 { get; set; }
        public double Ltd_com { get; set; }
        public double Ltd_win1 { get; set; }
        public double Ltd_win2 { get; set; }
        public double Lxtd_com { get; set; }
        public double Lxtd_win1 { get; set; }
        public double Lxtd_win2 { get; set; }
        public double Lfc_com { get; set; }
        public double Lfc_win1 { get; set; }
        public double Lfc_win2 { get; set; }
        public double Ldot_com { get; set; }
        public double Ldot_win1 { get; set; }
        public double Ld6_com { get; set; }
        public double Ld6_win1 { get; set; }
        public double Bop_com { get; set; }
        public double Bop_win1 { get; set; }
        public double Bop_win2 { get; set; }
        public double Bak_com { get; set; }
        public double Bak_win1 { get; set; }
        public double Bak_win2 { get; set; }
        public double Bxak_com { get; set; }
        public double Bxak_win1 { get; set; }
        public double Bxak_win2 { get; set; }
        public double Btd_com { get; set; }
        public double Btd_win1 { get; set; }
        public double Btd_win2 { get; set; }
        public double Bxtd_com { get; set; }
        public double Bxtd_win1 { get; set; }
        public double Bxtd_win2 { get; set; }
        public double Bfc_com { get; set; }
        public double Bfc_win1 { get; set; }
        public double Bfc_win2 { get; set; }
        public double Bdot_com { get; set; }
        public double Bdot_win1 { get; set; }
        public double Bd6_com { get; set; }
        public double Bd6_win1 { get; set; }
        public double Eop_com { get; set; }
        public double Eop_win1 { get; set; }
        public double Eop_win2 { get; set; }
        public double Eak_com { get; set; }
        public double Eak_win1 { get; set; }
        public double Eak_win2 { get; set; }
        public double Exak_com { get; set; }
        public double Exak_win1 { get; set; }
        public double Exak_win2 { get; set; }
        public double Etd_com { get; set; }
        public double Etd_win1 { get; set; }
        public double Etd_win2 { get; set; }
        public double Extd_com { get; set; }
        public double Extd_win1 { get; set; }
        public double Extd_win2 { get; set; }
        public double Efc_com { get; set; }
        public double Efc_win1 { get; set; }
        public double Efc_win2 { get; set; }
        public double Edot_com { get; set; }
        public double Edot_win1 { get; set; }
        public double Ed6_com { get; set; }
        public double Ed6_win1 { get; set; }
    }
}